name: Sync GitHub Issues & Pull Requests to Jira

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - review_requested
  workflow_run:
    workflows: [jira-issue-sync-pr-review]
    types:
      - completed
  issues:
  issue_comment:

concurrency:
  group: jira-sync-${{ github.event.pull_request.number || github.event.issue.number || github.event.workflow_run.id }}
  cancel-in-progress: true

jobs:
  sync_issues_to_jira:
    if: |
      contains(github.event.issue.labels.*.name, 'jira-sync') ||
      contains(github.event.pull_request.labels.*.name, 'jira-sync') ||
      github.event.workflow_run.event == 'pull_request_review'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Sync GitHub Issues & Pull Requests to Jira
        uses: ciscoecosystem/sync-jira-actions@40f433770e130cbab8a854e1572a8cdbefdb1f88 # v1.4.5
        with:
          sync_label: jira-sync
          status_field_id: 10740
          find_jira_retries: 0
          link_closing_issues: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_PASS: ${{ secrets.JIRA_PASS }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_PROJECT: DCNE
          JIRA_COMPONENT: mso-go-client
          JIRA_ISSUE_TYPE: GitHub Issue
